### ISSUE TITLE
Investigate the Full Contact API

### ISSUE THREAD

**Issue by mathetos** [WordImpress/WP-Business-Reviews#1]
This is the API that HelpScout uses to populate all the crazy data they show on our customers in the sidebar:
https://www.fullcontact.com/data/

They advertise a "Free API" but you do have to sign-up for it. I think it's worth looking into what it might look like to integrate with this. Maybe as an Add-on, or just a feature of the Pro version.

**Comment by DevinWalker** [comment]
I took a look at this and it's pretty cool for sure. I don't see however how this applies to the plugin except for if we were to build in some "Insights" which would then use the reviewers emails or another data point to pass through this API.  The free version only allows 100 per month and it goes up to $99/month after that for 2,500 matches. I don't think it's something we'd want to integrate with at this time after investigating. If we receive requests for it down the line we may reopen.
