### ISSUE TITLE
fix(admin-builder): facebook reviews pages save awkward naming

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/wp-business-reviews#108]
## Issue Overview

When you save a facebook page reviews collection it saves strangely:

![2018-04-19_22-53-25](https://user-images.githubusercontent.com/1571635/39032947-9f6f4040-4424-11e8-82f3-e0f9bfe9060a.png)

**Comment by kevinwhoffman** [comment]
This is because the Give Facebook page does not have a location set. Other pages that do have locations work as expected. I will add a condition to only display the ` - City, State` if they exist.
