### ISSUE TITLE
refactor(admin-menu): clean up admin menu for beta

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#118]
## User Story

As a WPBR user, I want a clear menu presentation so that I have a clear understanding of the various admin pages associated with the plugin.

## Acceptance Criteria

- [x] All WPBR pages are available under a single menu item.

## Possible Solution

- Reviews
    - All Reviews
    - Reviews Builder
    - Settings

## Visuals

Platforms, Review Sources, and Collections should be hidden per the image below.

![image](https://user-images.githubusercontent.com/1938671/39229403-aaa38736-4830-11e8-88f7-ea0a324e2dc7.png)

@DevinWalker if you have a different expectation let me know.

This should all be done by adjusting arguments in the `Post_Type` class where the post types are registered.

**Comment by DevinWalker** [comment]
@kevinwhoffman please review: https://invis.io/DHI7KHMJ598#/295793052_Review_Listings

This is the consolidated admin experience I'm going for where admins can add reviews and platforms to suit their needs.

**Comment by kevinwhoffman** [comment]
## Menu

- Collections/Builder - We should discuss the interplay of these two screens, because right now Collections are listed in the Builder launch screen.

## Single Review Screen

- Review Text - We should use a plain textarea for this field so that it matches the format of other platform reviews. None of the platforms support rich text, and the truncation logic for character counts would be thrown off by HTML markup in the review text.
- Review URL - This is the one field missing from the review editor that is present in all of the platform reviews. You can see I have it as an optional field below.

![wpbr-mockup-review-add-v01](https://user-images.githubusercontent.com/1938671/39774489-ff816b90-52c8-11e8-85e2-34ae4cc24f57.png)
