### ISSUE TITLE
fix(builder): php fatal error 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/wp-business-reviews#136]
## User Acceptance

As an `admin` when I create `facebook reviews in the builder` I expect it to `save properly` so that I can display them on my website.

![2018-05-07_21-37-35](https://user-images.githubusercontent.com/1571635/39738247-df67f386-523e-11e8-9687-b26c5de55a47.png)

## Video

I was attempting to create a video for Facebook to approve our page. I notice now we need to get re-approved. Then this happened:

https://goo.gl/46KTAs

**Comment by kevinwhoffman** [comment]
@DevinWalker I could not recreate locally after trying with two different Facebook pages. Let's jump on a call where I can see what the JSON string looks like before it is decoded into an array.

**Comment by kevinwhoffman** [comment]
I was unable to recreate. I did a fresh install and then connected. I also removed my access from Facebook and started from scratch. I don’t think it is related to the FB connection because you were able to get reviews. Once they are in the builder, Facebook is out of the picture.

**Comment by kevinwhoffman** [comment]
This appeared to be a one-time error. Closing.
