### ISSUE TITLE
feat(admin-review): customize single review edit screen

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#141]
## User Story

As a WPBR user, I want to edit all of the fields necessary for a review so that my custom reviews have the same fields as my API reviews.

## Acceptance Criteria

- [x] I can edit the following fields:
    - [x] Title
    - [x] Reviewer Name
    - [x] Rating
    - [x] Review Text (plain text so that it is formatted like API reviews)
    - [x] Review URL
    - [x] Review platform
    - [x] Reviewer image (upload and set manually)
- [x] When I save a 5-star rating, it is mapped to its corresponding term in the `wpbr_rating` taxonomy. For example, a 4-star rating gets the `80` term assigned to it.
- [x] When I save a platform, it is mapped to its corresponding term in the `wpbr_platform` taxonomy.

### Empty Screen
![single review edit copy 2x](https://user-images.githubusercontent.com/1938671/39949315-292d57d4-5548-11e8-81dc-435136925134.jpg)

### Populated Screen
![single review edit 2x](https://user-images.githubusercontent.com/1938671/39949316-293bf938-5548-11e8-8bc1-d7196aced63c.jpg)

## Possible Solution

It may be worth using `Includes/Serializer/Review_Serializer: save_from_post_array()` method to save the post. That way we are using the same functionality to save custom reviews as we are for API reviews and much of the work is done already.

**Comment by DevinWalker** [comment]
Resolved via https://github.com/WordImpress/wp-business-reviews/pull/143
