### ISSUE TITLE
feat(activation-banner): add activation banner

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#154]
## User Story

As a WPBR user, I want some type of direction as to where to begin after installation so that I'm not left wondering what to do next.

## Acceptance Criteria

- [ ] The banner appears after installation on the Plugins screen.
- [ ] The banner provides links to `Settings`, `Video Tutorials`, `Documentation`, and `Support`.

## Visuals

Give activation banner for reference.

![image](https://user-images.githubusercontent.com/1938671/41075930-fd0c2578-69dc-11e8-8cc2-ed226c83d798.png)

**Comment by mathetos** [comment]
This is my suggestion:

![image](https://user-images.githubusercontent.com/930724/41128704-d8ffdad0-6a63-11e8-8992-606e48d1ce1b.png)
