### ISSUE TITLE
feat(setting): add Disconnect option to Facebook Connect screen

### ISSUE THREAD

**Issue by mathetos** [WordImpress/wp-business-reviews#156]
We need to allow users to disconnect their Facebook integration with a click. The current plugin has this ability.

Currently, once you're connected, the only other option is to connect again.
![image](https://user-images.githubusercontent.com/930724/41113295-15d445b4-6a36-11e8-84ee-c442ce7f43d4.png)

**Comment by kevinwhoffman** [comment]
This is a regression. There is ability to disconnect, and your pages should also be listed here. I will look into it.

**Comment by kevinwhoffman** [comment]
Fixed in `feature/facebook` branch and is ready to go once the FB app gets approved.
