### ISSUE TITLE
feat(builder): allow Place ID to be entered directly

### ISSUE THREAD

**Issue by mathetos** [WordImpress/wp-business-reviews#194]
## User Story

As a business owner, I want to be able to provide my Place ID directly so that I can still access my reviews even though my business does not appear in search results.

## Current Behavior

I currently search for `WordXpress` in the builder and receive a notice with no option other than to reset search and try again:

> No results found. For best results, enter the entire business name, city, and state as they appear on the platform.

Searching for `WordXpress` in the Place ID finder also yields no result, however searching for `WordXpress` on Google Maps does show the business and reviews.

## Expected Behavior

I expect to be able to enter my Place ID as an alternative to searching my Business Name.

## Acceptance Criteria

- [x] I can enter my Business Name **OR** Place ID in the `Search Terms` field.
- [x] The `Location` field is not required if a Place ID is detected.

## Related

Feedback from Tevya:

> My business is the only one I've done it with so far: https://www.google.com/maps/place/WordXpress+-+WP+Maintenance+%26+Support/@47.5863296,-123.592003,3z/data=!4m2!3m1!1s0x0:0x232227f93926d06f?sa=X&ved=2ahUKEwjKtvqw2abcAhWMEnwKHQXOC78Q_BIwEnoECA0QCw

> PID: ChIJjaEeqKeLUocRb9AmOfknIiM

**Comment by kevinwhoffman** [comment]
I've confirmed via Postman that I can retrieve reviews for Tevya's business by including the Place ID in a [Place Details](https://developers.google.com/places/web-service/details) request. This effectively skips the step of searching for the business by name and location. This is good news as it means any user with Google Places reviews can use the plugin, even if they cannot be found in a text search.


## Recommended Solution

I propose we allow users to enter a Business Name **OR** Place ID into the `Search Terms` field. This avoids adding complexity to the UI and would only require clarification in the tooltip and placeholder text as shown below.

![image](https://user-images.githubusercontent.com/1938671/42895385-c7c6d61c-8a87-11e8-838c-0426e47e212b.png)

The [length of a Place ID](https://developers.google.com/places/place-id#id-overview) can vary, however we can make some safe assumptions to determine whether the user entered a business name or Place ID.

If the following are true, then assume a Place ID was entered and make a Place Details request:

- The trimmed string length is greater than 24 characters.
- The trimmed string has no spaces.
