### ISSUE TITLE
fix(reviews): Date showing an "Invalid" in Safari for Google and Yelp

### ISSUE THREAD

**Issue by mathetos** [WordImpress/wp-business-reviews#198]
## Bug Summary
Safari displays Invalid Date on reviews for Google and Yelp

## Bug Details
I'm testing your new plugin on my client's website and they sent me screenshots that show the reviews for both Google and Yelp say Invalid Date where the date of the review should be. In Google Chrome and Firefox the date shows up just fine.

## Screenshots

https://wpbusinessreviews.com/wp-content/uploads/2018/07/Screen-Shot-2018-07-18-at-4.46.43-PM.png, https://wpbusinessreviews.com/wp-content/uploads/2018/07/Screen-Shot-2018-07-18-at-4.46.51-PM.png

**Comment by kevinwhoffman** [comment]
Closing. This is fixed.
