### ISSUE TITLE
fix(google-places-request): prevent errors regarding daily quota

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#230]
## User Story

As a user, I want to avoid errors mentioning a daily quota so that I can access my Google reviews.

## Current Behavior

Some users are seeing the following error when searching for their business:

> You have exceeded your daily request quota from this API.

Here is the API response:

```js
{
    "error_message": "You have exceeded your daily request quota for this API.",
    "html_attributions": [],
    "results": [],
    "status": "OVER_QUERY_LIMIT"
}
```

## Expected Behavior

The search returns businesses matching the search query.

## Possible Solution

It's unlikely that multiple users are actually hitting the daily quota, unless that quota has dropped significantly in light of recent billing changes. It's possible the error could also result from accessing the API too quickly with multiple requests.

## Related

- https://secure.helpscout.net/conversation/639888088/23371/?folderId=2120004
- https://developers.google.com/maps/billing/understanding-cost-of-use#places-details
- https://stackoverflow.com/questions/38216519/you-have-exceeded-your-daily-request-quota-for-this-api-google-places-api-ios-s

**Comment by kevinwhoffman** [comment]
Here's a video showing steps to recreate:

https://drive.google.com/open?id=1mx0pwhKJRHs1VcPoXNOdfdM4SwmflSov

1. Create a new key in a new project.
2. Enter new key into plugin settings.
3. Add a Google collection.
4. Search for a business. This worked once for me.
5. Click "Get Reviews" and note the 500 error.
6. Click reset and search for business again. Now you should see: `You have exceeded your daily request quota from this API.`

**Comment by kevinwhoffman** [comment]
When I look at the API usage in Google API Console, it shows that the max limit per day is `1`.

![image](https://user-images.githubusercontent.com/1938671/44098950-808a1722-9faf-11e8-8242-819127438f29.png)

When I click the pencil to edit, I see this message indicating that billing is necessary to increase the limit.

![image](https://user-images.githubusercontent.com/1938671/44098974-90078180-9faf-11e8-8178-267a0014b157.png)

**Comment by mathetos** [comment]
Finally replicated this problem as well. The reason I couldn't replicate was because I was testing with `@wordimpress.com` which is a paid account. As soon as I tested with my personal unpaid account I see exactly what you are seeing BOTH with new projects and old projects. The quota says "1" and requires connecting billing in order to update it. Then I attached a billing account to it and now I see everything as unlimited.

The one caveat there is that I checked on the OLD project AFTER I added billing to that account. So it's possible that the OLD project was grandfathered until I added billing to the account, then they forced it. Wish I would have checked first, but I wanted to see the difference when the billing was attached.

**Comment by kevinwhoffman** [comment]
It took me a while to reliably trigger the daily quota error on a new key, but I figured out how to trigger it up front when the key is first saved. Here’s the plan that is in progress:

## 1. Communicate Billing Requirement on Initial Save

When a key is first saved, I am firing off two requests to the Google Places API. Since the daily quota of a free Google account is `1`, the first request will be successful. However this is misleading if we tell the user the API is connected because their very next search will fail. So I am firing a second request right away, and the result of that request is what actually gets saved. If it’s a free account (without billing enabled), then the request will fail with a notice as shown in the screenshot below. If billing is already enabled, then the second request will be successful and the status will be `Connected`.

![image](https://user-images.githubusercontent.com/1938671/44137883-fa5d9d90-a03f-11e8-9550-ac7c19c65474.png)

## 2. Communicate Billing Requirement within Builder

Existing users may have already entered API keys without billing enabled. In those cases, we should be able to handle the error and communicate the need to enable billing as shown below.

![image](https://user-images.githubusercontent.com/1938671/44138044-a5b961ec-a040-11e8-95fe-d6d8c016bf21.png)

## 3. Add Web Documentation

The links in the above notices will point to the following address:
https://wpbusinessreviews.com/documentation/platforms/google/#restrictions

The anchor will lead directly to a section with the following documentation:

### How to Enable Billing

As of July 16th, 2018, Google requires users to enable billing before accessing the Google Places API.

Enabling billing on the Google Cloud Platform should not result in any actual charges, however it is required in order to access your reviews over the API. To enable billing, follow the steps below:

1. Visit the following link to enable billing on the Google Cloud Platform: https://console.cloud.google.com/projectselector/billing/enable
2. Select the project in which you created the API key.
3. Click "Create Billing Account."
3. Enable billing by completing the Google Cloud Platform form.
4. After completion, return to WP Business Reviews Settings and re-save your API key.
5. Confirm that the Platform Status field now reads "Connected."

**Comment by mathetos** [comment]
Great work @kevinwhoffman I've updated the Doc per your provided text with minor alterations.
