### ISSUE TITLE
Add advanced setting: Uninstall Behavior

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#24]
## Issue Overview

The user should be able to decide whether to keep or remove plugin settings and reviews data when the plugin is uninstalled.

## Proposed Field

**Uninstall Behavior**
- Keep all plugin settings and reviews data if this plugin is uninstalled. (default)
- Remove all plugin settings and reviews data if this plugin is uninstalled.

## Tasks

- [x] Add field to Settings config.
- [ ] Add methods to `Deactivator` to clean up data.

**Comment by DevinWalker** [comment]
Resolved via https://github.com/WordImpress/wp-business-reviews/blob/develop/uninstall.php

I don't see any need to do anything with the `Deactivator` class right now.
