### ISSUE TITLE
Ensure collections do not cut off reviews

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#243]
## Current Behavior

Collections are being cut off in some browsers depending on the container width.

## Expected Behavior

Collections should render in their entirety and resize as needed.

## Visuals

From the user:
> My phone is an iPhone X running latest version of Safari.

![image](https://user-images.githubusercontent.com/1938671/44546958-88f1bc00-a6e7-11e8-958d-207c2838159c.png)

## Related

https://secure.helpscout.net/conversation/657092484/24866/

## Acceptance Criteria

- [ ] All collection formats (Gallery, List, Carousel) fit on screen without being cropped in iPhone X Safari (use BrowserStack to test).

**Comment by marutim** [comment]
We have a report from the same user of a similar behavior in an iMac with Safari for the sidebar widget. I can replicate the same in my Macbook in Chrome.
HS link: https://secure.helpscout.net/conversation/651238764/24271/

**Comment by telizarose** [comment]
This also happens on Chrome browsers when there is not enough room on the screen for desktop and on mobile. 
<img width="1280" alt="screen shot 2018-08-28 at 11 21 12 am" src="https://user-images.githubusercontent.com/38927530/44743079-544e7d80-aab6-11e8-91a1-bcba5d8bd877.png">
![screenshot_20180828-104849_chrome](https://user-images.githubusercontent.com/38927530/44743080-544e7d80-aab6-11e8-857c-010f8b092164.jpg)

**Comment by mathetos** [comment]
You can see that live on this site:
https://www.ajlocksmith.com/reviews/

I wonder if it would be more stable to put the border and padding on the `<article>` rather than the first child `<div>`?

Here's the issue in Inspector:
![image](https://user-images.githubusercontent.com/930724/44743872-852fb200-aab8-11e8-8242-834a6a7d1f53.png)

**Comment by kevinwhoffman** [comment]
Another report: http://test.trekpyrenees.com/testimonials/

I will try to make sure all of the reported sites in this thread are rendering correctly before closing.

**Comment by kevinwhoffman** [comment]
It turns out these are not really browser-specific bugs, but rather a combination of problems outlined in the cases below. I'm summarizing the problems here and will add permanent fixes in my PR.

## Case 1

https://www.ajlocksmith.com/reviews/

Problem is related to the `320px` minmax setting which is preventing the review from shrinking smaller than `320px` and therefore being cut off. Lowering that value resolves the issue according to my tests in dev tools.

```css
.wpbr-wrap.wpbr-wrap .wpbr-collection--auto-fit {
	grid-template-columns: repeat(auto-fit,minmax(320px,1fr));
}
```

## Case 2

http://test.trekpyrenees.com/testimonials/

The theme does not have `box-sizing: border-box;` set on the front end, so we should add the following rule to the plugin, which resolves the issue according to my tests in dev tools.

```css
.wpbr-wrap * {
		box-sizing: border-box;
}
```

## Case #3

https://secure.helpscout.net/conversation/651238764/24271/
https://www.sandandsteelfitness.com/

Problem is a combination of Cases 1 and 2. Once we fix the minmax issue and set the box-sizing, then this site's issue will be resolved.
