### ISSUE TITLE
Write npm task to build Free and Pro versions of plugin

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#27]
## Issue Overview

Since Free and Pro plugins share the same code base, an npm task can be used to package up the plugins into their respective packages.

`npm run build` - package the Pro version

- Minify/Concatenate assets.

`npm run build --free` - package the Free version

- Minify/Concatenate assets.
- Search and replace strings in the plugin header of `wp-business-reviews.php`.
- Delete the `includes/pro` directory.

@DevinWalker I could use your feedback here regarding any steps that this task could automate in terms of packaging up the two versions of the plugin.

**Comment by kevinwhoffman** [comment]
Following discussion of naming conventions in existing Yelp plugins, @DevinWalker recommends we keep the directory name and main plugin file the same across Free and Pro plugins:

```
Directory: wp-business-reviews
Main Plugin File: wp-business-reviews.php
Plugin Name: WP Business Reviews
Plugin URI: https://wpbusinessreviews.com
```

That means the only renaming that the npm script has to do is rename `WP Business Reviews` to `WP Business Reviews Pro`.

For simplicity, version numbers will be kept in sync across Free and Pro plugins.

**Comment by DevinWalker** [comment]
We're going pro only
