### ISSUE TITLE
Keep Internationalization in mind

### ISSUE THREAD

**Issue by mathetos** [WordImpress/WP-Business-Reviews#3]
Some users display reviews from business across different countries and languages. It would be best if we can allow users to set the language directly in each widget and/or shortcode. That way they can display different review instances in different languages either on the same page or different pages.

WPML support would be a big bonus as well.

**Comment by kevinwhoffman** [comment]
The majority of content displayed by the plugin on the front-end is user-generated content from the review platforms, so we don't have control over translating that content. Any strings output by the plugin are wrapped in gettext functions, and will respect the WordPress locale.

**Comment by DevinWalker** [comment]
👍
