### ISSUE TITLE
Complete plugin architecture

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#34]
## Issue Overview

I began development by adding `views` directories alongside their respective PHP classes in the `includes` directory. It seemed like a good idea at the time to keep views in close proximity to classes. However, in practice this results in a lot of `views` directories and makes it hard to find the view you're looking for when working on markup or styles.

I've since come across other projects that keep all view files in a `views` directory in the root of the plugin. This has proven easier on development and it makes sense to keep them separate from the plugin logic.

## Target Architecture

```
+ wp-business-reviews
|- assets (CSS, JS, images, fonts)
|- includes (business and application logic)
|- configs (configuration files consumed by the includes)
|- views (presentation markup)
|- vendor (Composer dependencies created during build)
|- node_modules (npm dependencies created during build)
```

## Tasks

- [ ] Move remaining views out of `includes` and into the root `views` directory.

## Notes

@DevinWalker This is a minor change that requires moving some of the remaining views into the root `views` directory. I just thought it would be helpful to document so we have a shared understanding of the plugin's architecture.

**Comment by DevinWalker** [comment]
Cool, makes sense. 👍
