### ISSUE TITLE
Consider adding support for business search endpoint to Reviews Builder

### ISSUE THREAD

**Issue by Benunc** [WordImpress/WP-Business-Reviews#4]
currently we are not supporting the search functionality that exists in our current Yelp plugin, which leaves existing users without the ability to transition from one product to the other.

If a user (say, a real estate agent) is using yelp search widgets currently, they are not supported in the new plugin, and as of april our old plugin will no longer function, due to v 2 endpoints. 

I have had one user request for this, and @marutim and I will keep track of new ones by commenting here.

**Comment by kevinwhoffman** [comment]
Thanks for bringing this up @Benunc. Let's move this conversation to #11.
