### ISSUE TITLE
Consider faker.js integration

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#76]
## Issue Overview

When an agency or developer is first starting to work with a client, they may not have the review volume to adequately demonstrate what the plugin has to offer. faker.js could provide that volume of data that is a step above static `FirstName LastName` and `Lorem ipsum...`

If integrated, faker.js would be considered its own platform that returns review sources and reviews just like any other. It would be selected in the Builder launch screen just like Google Places or Facebook is selected, and it could also be disabled in settings.

## Related

- [GitHub](https://github.com/Marak/faker.js)
- [Demo](https://rawgit.com/Marak/faker.js/master/examples/browser/index.html)

**Comment by kevinwhoffman** [comment]
Closing. I don't think this is necessary nor would it result in believable reviews. We would be better off including a static JSON file containing placeholder reviews.

**Comment by mathetos** [comment]
I can see that a static json would be more practical. Just putting this here for future reference, since it has a strong API as well that might come in handy with the json file:
https://randomuser.me/documentation
