### ISSUE TITLE
Add useful columns to the Reviews list table

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#8]
## Issue Overview

The current list table doesn't give any indication as to contents of the review. The table could be enhanced to view many reviews at a glance without having to click into them.

The columns should include:

- View button
- Review Excerpt (the contents of the review up to a certain character count)
- Reviewer
- Rating
- Platform
- Date

## Tasks

- [x] Mockup how the table should appear.
- [ ] Update the list table to include the columns above.

**Comment by kevinwhoffman** [comment]
@DevinWalker I'm assigning this to you, but note there is a blocking issue that I need to resolve before you can start on this.

**Comment by DevinWalker** [comment]
Ok sounds good 👍
