### ISSUE TITLE
fix(admin-settings): when returning from tab's platform checkbox icon should be green 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/wp-business-reviews#90]
## Issue Overview

After returning from a connected platform the icon should be green like it is upon subsequent refresh:

![2018-02-22_00-03-55](https://user-images.githubusercontent.com/1571635/36526765-53b19f6e-1764-11e8-91f6-c25fd343c7de.png)

When refreshing:

![2018-02-22_00-07-18](https://user-images.githubusercontent.com/1571635/36526782-60374c02-1764-11e8-92e8-ba4cfe2d9ec4.png)

**Comment by kevinwhoffman** [comment]
Noted in #49. This issue will be addressed there.
