### ISSUE TITLE
doc(admin-settings): yelp - add one-click app creation link like in current plugin

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/wp-business-reviews#91]
## Issue Overview

I noticed the current yelp widget pro has this link: https://www.yelp.com/developers/v3/manage_app

It appears to make it an almost "one-click" method of retrieving and API key. I noticed the current link doesn't have this link:

![2018-02-22_00-08-17](https://user-images.githubusercontent.com/1571635/36526923-cdb033e8-1764-11e8-8a49-578c4b49160d.png)

If I'm not mistaken, adding this would help the user create an app and create a key. 

### Considerations

1. Using a URL that we can update in case this URL changes
2. Should we just refer them to our documentation?

**Comment by kevinwhoffman** [comment]
We decided to point all inline docs to the videos tab.
