### ISSUE TITLE
refactor(builder): review video and break out issues

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/WP-Business-Reviews#92]
## Issue Overview

Coming into the review builder with fresh eyes this is my experience that I had this evening. Overall, I really enjoy the interface. That said, I think we can improve in several places. I wanted to provide some videos to start the conversation about the overall building experience and how we may improve it across all platforms and per platform.

### Facebook Building Review

 https://goo.gl/QxsvWz

### Yelp Building Review

https://goo.gl/Udqiin

---

I'd like to break the separate issues that are brought up throughout the videos into separate issues if there already aren't ones created.

Those issues include:

1. After selecting a page/business it's not evident that you should move on the "presentation" customization
2. Giving your "review set" a title isn't evident nor a thought the user should give mind to. I think we should make this nearly transparent to the user. Maybe give a naming convention that is self evident like "Review Set #123 - Lucha Libre Tacos - San Diego, CA - 02-03-18", "Mashup #123 - Lucha Libre Tacos, San Diego, CA - 02:30:12:12:34:39". Or present them with a
3. The functionality for the "Settings" button that toggles the right panel isn't evident. I thought it would take me to the "Settings" page rather than toggle the sidebar. Is toggling the sidebar even necessary? The only reason I can see to toggle it would be to view the reviews more closely to how they would appear on the site. I recommend changing this button to a "Preview" button that then allows us to preview the set in a modal or something that's more evident. This isn't a huge priority since most users probably will want to connect, build, then display quickly on their sites. Let's discuss best options here more in person. 
4. Additional mentions throughout the video... the above is only what I recall from the overview but we should spend some additional time discussing once you've had a chance to review.

**Comment by kevinwhoffman** [comment]
@DevinWalker Thanks for feedback. Issues have been broken out and collected in Epic #99.

**Comment by DevinWalker** [comment]
Thanks @kevinwhoffman
