### ISSUE TITLE
refactor(builder): make it obvious where to start building reviews

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#93]
## Issue Overview

@DevinWalker mentioned that when landing in the builder, the user may not know where to begin searching for reviews. We should improve the clarity of that first impression and direct them where to begin.

## Possible Solution

1. Add some type of visual indicator or tooltip that draws attention to the platform search box.
2. Replace dummy reviews with simplified placeholders. See mockup below.

## Mockup

Current: The dummy text adds a lot of clutter to the page.

![image](https://user-images.githubusercontent.com/1938671/36558780-21cf3648-17da-11e8-9592-1e71097962ef.png)

Proposed: By replacing the dummy text with simple shapes, it will be more obvious that these are placeholder reviews and draw more attention to the settings.

![image](https://user-images.githubusercontent.com/1938671/36558739-f9922b36-17d9-11e8-9a44-31866ca13dbf.png)

**Comment by DevinWalker** [comment]
@kevinwhoffman the blank reviews like that definitely will help. I propose adding a simple tooltip to the top and consider adding tour/welcome flow like some apps have. Maybe a feature intro library like https://github.com/usablica/intro.js/

**Comment by DevinWalker** [comment]
@kevinwhoffman what do you think of something like this:

![tooltip](https://user-images.githubusercontent.com/1571635/36575087-c58b6fcc-17fd-11e8-8229-46338c4ce96d.png)

**Comment by kevinwhoffman** [comment]
@DevinWalker I like it. Here's what I recommend.

- Give each section header a tooltip in the same style of the existing tooltips.
- Activate the top section header's tooltip 1 second after page load.
- Deactivate it if the tooltip icon is hovered OR after the first change in the search fields. 

![image](https://user-images.githubusercontent.com/1938671/36575786-cc9d7bda-181a-11e8-8321-0f9ad9f9cace.png)

**Comment by mathetos** [comment]
> "Automatically activate the top section header's tooltip 1 second after page load."

I'd also suggest that the first section, "Review Source", scroll open one second after page load, while the next sections remain closed.
