### ISSUE TITLE
refactor(builder): improve clarity of controls toggle

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#98]
## Issue Overview

@DevinWalker reported:

> The functionality for the "Settings" button that toggles the right panel isn't evident. I thought it would take me to the "Settings" page rather than toggle the sidebar. Is toggling the sidebar even necessary? The only reason I can see to toggle it would be to view the reviews more closely to how they would appear on the site. I recommend changing this button to a "Preview" button that then allows us to preview the set in a modal or something that's more evident. This isn't a huge priority since most users probably will want to connect, build, then display quickly on their sites. Let's discuss best options here more in person.

I agree the current implementation isn't as clear as it could be, but I do think it is necessary to have the ability to hide the settings especially on smaller screens.

## Proposed Solution

This is the Customizer's solution for hiding controls. It is pinned to the bottom of the sidebar which makes it's purpose very clear because it's attached to the thing that it hides. I think we could do something similar.

![image](https://user-images.githubusercontent.com/1938671/36564260-a97f4f0a-17ea-11e8-86be-8c41292caceb.png)

**Comment by DevinWalker** [comment]
@kevinwhoffman yeah that's nice. I like going that route.

**Comment by kevinwhoffman** [comment]
Closing. The existing gear toggle works well enough and is consistent with Gutenberg-style toggling.
